# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  hiking_project_api_key: <%= ENV["hiking_project_api_key"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd969ab6ac4f0a81a8403e96062c5ea1ecea5bec51939bdcf0f46910ea86b85e752234dc4b52c8419974511f69b85727888017a490a2a9559f627041fc86a1cd

test:
  secret_key_base: bd969ab6ac4f0a81a8403e96062c5ea1ecea5bec51939bdcf0f46910ea86b85e752234dc4b52c8419974511f69b85727888017a490a2a9559f627041fc86a1cd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
